---
destination : ~/Sites/minosniu.net
lsi         : false
highlight   : true
permalink   : none
markdown    : Kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md

maruku:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/

    
